export const FETCH_TUTORS_DATA_INIT = 'FETCH_TUTORS_DATA_INIT';
export const FETCH_TUTORS_DATA_SUCCESS = 'FETCH_TUTORS_DATA_SUCCESS';
export const FETCH_TUTORS_DATA_FAILURE = 'FETCH_TUTORS_DATA_FAILURE';
