export const FETCH_TUTORS_DATA_INIT = 'FETCH_TUTORS_DATA_INIT';
export const FETCH_TUTORS_DATA_SUCCESS = 'FETCH_TUTORS_DATA_SUCCESS';
export const FETCH_TUTORS_DATA_FAILURE = 'FETCH_TUTORS_DATA_FAILURE';
export const APPLY_FILTER = 'APPLY_FILTER';
export const APPLY_SORT = 'APPLY_SORT';
export const SHOW_ALL_TUTORS = 'SHOW_ALL_TUTORS';
